### ISSUE TITLE
Support 32-bit RHEL/CentOS

### ISSUE THREAD

**Issue by tpetchel** [chef-cookbooks/httpd#48] opened 2015-09-18 12:00 UTC
A Learn Chef user reported failures running this cookbook on a 32-bit CentOS installation.

This thread contains the details, including a gist of the output from his chef-client run:
https://learn.chef.io/manage-a-web-app/rhel/apply-and-verify-your-web-server-configuration/#comment-2258168966

If we're unable to support x86, let's clarify that in the README and on Learn Chef.

**Comment by 4current** [comment] 2015-09-30 11:07
Perhaps the problem is here in httpd/libraries/helpers_rhel.rb
```
      def libarch
        return 'lib64' if node['kernel']['machine'] == 'x86_64'
        return 'lib64' if node['kernel']['machine'] == 'i686'
      end
```

**Comment by brianhays** [comment] 2015-11-22 22:28
Looks like this issue was fixed and merged here: https://github.com/chef-cookbooks/httpd/pull/50

**Comment by tas50** [comment] 2016-05-01 18:12
Closing since this is fixed

**Closed** 2016-05-01 18:12 UTC
